# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            MistaTwista
tagline:          'Thoughts'
description:      'SELECT interesting FROM world'
url:              https://mistatwista.github.io
baseurl:          /

author:
  name:           'Maxim Kernozhitskiy'
  url:            https://mistatwista.github.io

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://mistatwista.github.io

gems:
  - jekyll-paginate
  - jekyll-gist

